apiVersion: v1 #annotations are used to select special charectors & outside resources
kind: Pod
metadata:
  name: annotations
  annotations:
    build URL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx