# echo -n 'admin' | base64 -->encode the data as YWRtaW4=
# echo -n 'admin123' | base64 --> encodes the password as YWRtaW4xMjM=
apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
type: Opaque
data:
  username: YWRtaW4=    #encrypted format of data and password
  password: YWRtaW4xMjM=

# kubectl delete secret dotfile-secret command to delete secrets what you created


