apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: frontend
    tier: web
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  # replicaset use these lables to find the pods for creating desired number of replicas 
    matchLabels:
      app: frontend
      tier: web
  template:
    metadata:
      labels:
        tier: web
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx-stable-perl
